### ISSUE TITLE
Obter as informações do Smartphone

### ISSUE THREAD

**Issue by Revokee** [Revokee/PCS2044#4]
Obter localização do smartphone Android

**Comment by cpuodzius** [comment]
No branch cassius-mobile eu iniciei a implementação e já existe um service que escreve periodicamente no log, durante a vida do App principal.

**Comment by cpuodzius** [comment]
O @lucasbcoelhoGitHub implementou um serviço que obtém periodicamente a posição do entregador. Eu implementei uma class (Task) que se comunica com o servidor fazendo GETs e recebendo JSONs de resposta.
