### ISSUE TITLE
Documento de Engenharia de Produto da sala

### ISSUE THREAD

**Issue by cpuodzius** [Revokee/PCS2044#9]
Verificar o atual estado desse documento e adicionar no repositório, se pronto.

**Comment by martedesco** [comment]
Modificada a estrutura organizacional da empresa em camadas, adicionada a descrição de todos stakeholders envolvidos no processo, adicionado diagrama da estrutura organizacional, redesenho e  elaboração do BPMN (descrição do processo de negócio) e adicionada descrição breve da regra de negócio desenvolvida por cada stakeholder.

Documento adicionado na pasta Documentos

**Comment by cpuodzius** [comment]
Gera um pdf do documento e põe junto ao docx, please? Docx não é amigo de Linux...

**Comment by martedesco** [comment]
.odt e .pdf gerado em Documentos
